### ISSUE TITLE
Rails 4.x compatability

### ISSUE THREAD

**Issue by itay-grudev** [oliverguenther/openproject-revisions#2]
Your `Gemfile` specifies:

``` ruby
s.add_dependency "rails", "~> 3.2.14"
```

which makes your project incompatible with Rails 4.x and thus I cannot add it to my Open Project.

**Comment by itay-grudev** [comment]
Just for the record that translates to `3.2.13 <= rails < 3.3`.

**Comment by mabentwickeltsich** [comment]
Dear @itay-grudev,

The release of this plugin for OpenProject 4.x (branch [dev)](https://github.com/oliverguenther/openproject-revisions/tree/dev) uses Rails 3. 
[openproject-revisions](https://github.com/oliverguenther/openproject-revisions) is deprecated in OpenProject 5.x and 6.x even if there is a branch [feature/5.0-compatibility](https://github.com/oliverguenther/openproject-revisions/tree/feature/5.0-compatibility).

If you are using OpenProject 5.x, you only need [openproject-revisions_git](https://github.com/oliverguenther/openproject-revisions_git/tree/release/5.0). Make sure you clone branch `release/5.0` and follow the instructions in the same branch which are updated.

There is no release of [openproject-revisions_git](https://github.com/oliverguenther/openproject-revisions_git) for OpenProject 6.X at the moment.

Cheers
Luis

**Comment by itay-grudev** [comment]
I see. Thanks.
